"""empty message

Revision ID: 533fabf56b38
Revises: None
Create Date: 2015-08-02 11:53:42.230950

"""

# revision identifiers, used by Alembic.
revision = '533fabf56b38'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tracking_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracking_visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('browser', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('event', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('location_full', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['tracking_site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracking_visit')
    op.drop_table('tracking_site')
    op.drop_table('users_user')
    ### end Alembic commands ###
